const user = {
    firstName: 'Juan',
    lastName: 'Schcolnik',
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
    score: 8,
  };

  const opponent = {
    firstName: 'Oli',
    lastName: 'Sanguinetti',
    image:
      'https://www.dzoom.org.es/wp-content/uploads/2020/02/portada-foto-perfil-redes-sociales-consejos.jpg',
    score: 7,
  };

export const TriviaHistoryMocked = [
    {
      user: user,
      opponent: opponent,
      triviaId: '1',
      date: new Date(),
    },
    {
      user: {
        firstName: 'Juan',
        lastName: 'Schcolnik',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
        score: 5,
      },
      opponent: opponent,
      triviaId: '2',
      date: new Date(),
    },
    {
      user: {
        firstName: 'Juan',
        lastName: 'Schcolnik',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
        score: 7,
      },
      opponent: opponent,
      triviaId: '3',
      date: new Date(),
    },
    {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      {
        user: user,
        opponent: opponent,
        triviaId: '1',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 5,
        },
        opponent: opponent,
        triviaId: '2',
        date: new Date(),
      },
      {
        user: {
          firstName: 'Juan',
          lastName: 'Schcolnik',
          image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Foto_Perfil_.jpg',
          score: 7,
        },
        opponent: opponent,
        triviaId: '3',
        date: new Date(),
      },
      
  ]; 